### ISSUE TITLE
Light green color

### ISSUE THREAD

**Issue by mfoucht** [ianjwhitmore/ecotrust-northwest-community-forests#12]
Flipping through pages, I think we need to set some parameters about the use of the Light green color. In some instances, it works for me - big blocks of color seem ok, but when it's used for a subhed or an outlined button, anything small and thin, it makes the item hard to see. What are our options for incorporating our other colors in here?

**Comment by ianjwhitmore** [comment]
We can customize this to a point but there should be a system in place so that you and client are setting colors every time they add text or buttons. 

If you want to give me a punch list I can work on the stylings.

For instance...

Outlined Button: Border = Gold, hover background = Gold
Solid Button: Background = Light Green, Hover = Dark Green

Event Titles = Dark Green
Footer Links = White, Hover = Light Green

I hope that helps.

**Comment by mfoucht** [comment]
OK that makes sense. @sarahmagrish - tagging you since I can't seem to tag Helday yet. I think this is something we need his eyes on.

**Comment by hbdelacruz** [comment]
Here are my thoughts on colors:

HOMEPAGE:

Make large bar at the top dark gray
Make Get Started gold
Make Learn More gold

Outlined Button: Border = gold, cover background= white, text = gold
Solid Button: Background = light green, hover = dark green

Event Titles: Text = black, hover text = dark green
Event Location: Gold

FOREST STORIES > PROFILES: 

Header text = black, header hover text = dark green

FOREST STORIES > CASE STUDIES:

Header text = black, header hover text = dark green 
CONTACT:

Solid Send Button = light green, text = white, hover = dark green

**Comment by ianjwhitmore** [comment]
Hey there! Helday and I sat down and worked through most of these and made some further changes.

Let us know what you think and we can continue to dial it all in.

**Comment by ianjwhitmore** [comment]
@sarahmagrish Any further thoughts or revisions on color use throughout?

**Comment by sarahmagrish** [comment]
no -- looking very sharp! thanks.
