### ISSUE TITLE
Site is pulling incorrect date for events

### ISSUE THREAD

**Issue by mfoucht** [ianjwhitmore/ecotrust-northwest-community-forests#32]
I tried to publish an upcoming event, but the site is pulling a date in 1970 (!). http://ianwhitmore.com/clients/ecotrust/nwcf/event/coalition-steering-committee-meeting/?preview=true

**Comment by ianjwhitmore** [comment]
Managed to sort this out. One thing to note this plugin doesn't display multi-day events intuitively so  my advice is to post multi-day events for each individual day.

I am hesitant to try and hack an Events theme to correct for this. (Currently it will display the end date instead of the start day for a multi-day event)
